version: '3'
services:
  api:
    restart: always
    build: ./API
    depends_on:
      - postgree
    ports:
      - 8080:8080
    environment:
      - DB_PORT=5055
  postgree:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5055
  adminer:
    restart: always
    image: adminer
    ports:
      - 8888:8080